site_name: 測量学実習第一・第二 指導書
theme:
  name: material
  language: ja
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
nav:
  - ホーム: index.md
  - 1. はじめに:
      - 概要: 01/index.md
      - 1.1 測量実習の目的: 01/01_測量実習の目的.md
      - 1.2 スケジュール・集合場所・班分け: 01/02_スケジュール・集合場所・班分け.md
      - 1.3 留意事項: 01/03_留意事項.md
      - 1.4 シラバス: 01/04_シラバス.md
      - 1.5 実習の評価: 01/05_実習の評価.md
      - 1.6 準備:
          - 概要: 01/06/index.md
          - 1.6.1 指導書（電子版）の使い方: 01/06/01_指導書(電子版)の使い方.md
          - 1.6.2 フォルダの作成: 01/06/02_フォルダの作成.md
          - 1.6.3 エクスプローラ上でのファイル拡張子の表示: 01/06/03_エクスプローラ上でのファイル拡張子の表示.md
          - 1.6.4 もしフリーズしたら: 01/06/04_もしフリーズしたら.md
          - 1.6.5 Excel のインストール: 01/06/05_Excelのインストール.md
          - 1.6.6 QGIS のインストール: 01/06/06_QGISのインストール.md
          - 1.6.7 関数電卓による60進法（度分秒）計算の習得: 01/06/07_関数電卓による60進法(度分秒)計算の習得.md
  - 2. 実習の基本的事項:
      - 概要: 02/index.md
      - 2.1 測量実習の作業順序: 02/01_測量実習の作業順序.md
      - 2.2 測量実習における注意事項:
          - 概要: 02/02/index.md
          - 2.2.1 測量の計画（予習）: 02/02/01_測量の計画(予習).md
          - 2.2.2 準備: 02/02/02_準備.md
          - 2.2.3 踏査: 02/02/03_踏査.md
          - 2.2.4 選点: 02/02/04_選点.md
          - 2.2.5 造標: 02/02/05_造標.md
          - 2.2.6 観測: 02/02/06_観測.md
          - 2.2.7 器具の返却: 02/02/07_器具の返却.md
          - 2.2.8 観測結果の処理: 02/02/08_観測結果の処理.md
      - 2.3 レポートについて:
          - 概要: 02/03/index.md
          - 2.3.1 良いレポートとは: 02/03/01_良いレポートとは.md
          - 2.3.2 レポートを書く目的: 02/03/02_レポートを書く目的.md
          - 2.3.3 レポートの執筆要領: 02/03/03_レポートの執筆要領.md
      - 2.4 図面について:
          - 概要: 02/04/index.md
          - 2.4.1 注意点: 02/04/01_注意点.md
          - 2.4.2 図面の表現方法: 02/04/02_図面の表現方法.md
  - 3. 測量器具と取り扱い:
      - 概要: 03/index.md
      - 3.1 概要: 03/01_概要.md
      - 3.2 器具一覧と片づけ方: 03/02_器具一覧と片づけ方.md
      - 3.3 トータルステーション:
          - 概要: 03/03/index.md
          - 3.3.1 各部の名称: 03/03/01_各部の名称.md
          - 3.3.2 構造および測角の機構: 03/03/02_構造および測角の機構.md
          - 3.3.3 測距の機構（光波距離計としての機能）: 03/03/03_測距の機構(光波距離計としての機能).md
          - 3.3.4 三脚: 03/03/04_三脚.md
          - 3.3.5 プリズム: 03/03/05_プリズム.md
          - 3.3.6 仕様: 03/03/06_仕様.md
      - 3.4 トータルステーションの基本的な使い方1):
          - 概要: 03/04/index.md
          - 3.4.1 据え付け（整準と致心）: 03/04/01_据え付け(整準と致心).md
          - 3.4.2 電源を入れる: 03/04/02_電源を入れる.md
          - 3.4.3 操作パネル部の名称と基本のキー操作: 03/04/03_操作パネル部の名称と基本のキー操作.md
          - 3.4.4 モード: 03/04/04_モード.md
          - 3.4.5 ディスプレイ表示とその操作: 03/04/05_ディスプレイ表示とその操作.md
          - 3.4.6 バッテリーの装着、取り外し: 03/04/06_バッテリーの装着、取り外し.md
          - 3.4.7 望遠鏡のピント合わせとターゲットの視準: 03/04/07_望遠鏡のピント合わせとターゲットの視準.md
          - 3.4.8 角度の測定: 03/04/08_角度の測定.md
          - 3.4.9 距離の測定: 03/04/09_距離の測定.md
          - 3.4.10 エラーメッセージ: 03/04/10_エラーメッセージ.md
      - 3.5 レベル:
          - 概要: 03/05/index.md
          - 3.5.1 ティルティングレベル（微動レベル）2): 03/05/01_ティルティングレベル(微動レベル)2).md
          - 3.5.2 ティルティングレベルによる水準測量: 03/05/02_ティルティングレベルによる水準測量.md
          - 3.5.3 標尺: 03/05/03_標尺.md
          - 3.5.4 ティルティングレベルによるスタジア測量: 03/05/04_ティルティングレベルによるスタジア測量.md
      - 3.6 巻尺: 03/06_巻尺.md
      - 3.7 その他の器具: 03/07_その他の器具.md
      - 3.8 測量機器・器具の取り扱い上の注意:
          - 概要: 03/08/index.md
          - 3.8.1 トータルステーションについて: 03/08/01_トータルステーションについて.md
          - 3.8.2 ティルティングレベル: 03/08/02_ティルティングレベル.md
          - 3.8.3 その他（三脚、標尺、ポール、巻尺等）: 03/08/03_その他(三脚、標尺、ポール、巻尺等).md
  - 4. 角測量:
      - 概要: 04/index.md
      - 4.1 概要: 04/01_概要.md
      - 4.2 器具: 04/02_器具.md
      - 4.3 作業手順:
          - 概要: 04/03/index.md
          - 4.3.1 外業: 04/03/01_外業.md
          - 4.3.2 内業: 04/03/02_内業.md
      - 4.4 レポート（#1）: 04/04_レポート(#1).md
      - 4.5 野帳：角測量: 04/05_野帳：角測量.md
  - 5. 距離測量:
      - 概要: 05/index.md
      - 5.1 概要: 05/01_概要.md
      - 5.2 器具: 05/02_器具.md
      - 5.3 作業手順:
          - 概要: 05/03/index.md
          - 5.3.1 外業: 05/03/01_外業.md
          - 5.3.2 内業: 05/03/02_内業.md
      - 5.4 レポート（#2）: 05/04_レポート(#2).md
      - 5.5 野帳：距離測量: 05/05_野帳：距離測量.md
  - 6. 水準測量:
      - 概要: 06/index.md
      - 6.1 概要: 06/01_概要.md
      - 6.2 器具: 06/02_器具.md
      - 6.3 作業手順:
          - 概要: 06/03/index.md
          - 6.3.1 作業の概要: 06/03/01_作業の概要.md
          - 6.3.2 作業の流れ: 06/03/02_作業の流れ.md
          - 6.3.3 外業: 06/03/03_外業.md
          - 6.3.4 内業: 06/03/04_内業.md
      - 6.4 レポート（#3）: 06/04_レポート(#3).md
      - 6.5 野帳：水準測量: 06/05_野帳：水準測量.md
  - 7. 地形測量:
      - 概要: 07/index.md
      - 7.1 目的: 07/01_目的.md
      - 7.2 使用器具: 07/02_使用器具.md
      - 7.3 作業全体の流れ: 07/03_作業全体の流れ.md
      - 7.4 踏査・選点: 07/04_踏査・選点.md
      - 7.5 測点1の座標と基準線1-2の方位角の測定:
          - 概要: 07/05/index.md
          - 7.5.1 作業の流れと注意事項: 07/05/01_作業の流れと注意事項.md
          - 7.5.2 野帳：測点1の座標及び、測線1-2の方位角の測量: 07/05/02_野帳：測点1の座標及び、測線1-2の方位角の測量.md
      - 7.6 水準測量:
          - 概要: 07/06/index.md
          - 7.6.1 作業の流れと注意事項: 07/06/01_作業の流れと注意事項.md
          - 7.6.2 レポート（#5）: 07/06/02_レポート(#5).md
          - 7.6.3 野帳：水準測量: 07/06/03_野帳：水準測量.md
      - 7.7 トラバース測量:
          - 概要: 07/07/index.md
          - 7.7.1 作業の流れと注意事項: 07/07/01_作業の流れと注意事項.md
          - 7.7.2 レポート（#6）: 07/07/02_レポート(#6).md
          - 7.7.3 野帳：トラバース測量: 07/07/03_野帳：トラバース測量.md
      - 7.8 細部測量:
          - 概要: 07/08/index.md
          - 7.8.1 作業の流れと注意事項: 07/08/01_作業の流れと注意事項.md
          - 7.8.2 レポート（#7）: 07/08/02_レポート(#7).md
      - 7.9 後片付け: 07/09_後片付け.md
      - 7.10 野帳：細部測量: 07/10_野帳：細部測量.md
  - 8. コンピュータによるデータ処理:
      - 概要: 08/index.md
      - 8.1 目的: 08/01_目的.md
      - 8.2 GISとは:
          - 概要: 08/02/index.md
          - 8.2.1 GISで扱うデータの構造: 08/02/01_GISで扱うデータの構造.md
          - 8.2.2 座標系について: 08/02/02_座標系について.md
      - 8.3 練習データでのデータ処理:
          - 概要: 08/03/index.md
          - 8.3.1 作業手順: 08/03/01_作業手順.md
          - 8.3.2 レポート（#4）: 08/03/02_レポート(#4).md
      - 8.4 Microsoft Excelでの座標の計算:
          - 概要: 08/04/index.md
          - 8.4.1 作業前の準備: 08/04/01_作業前の準備.md
          - 8.4.2 トラバース測量データ処理: 08/04/02_トラバース測量データ処理.md
          - 8.4.3 QGISへ取り込むためのデータ処理: 08/04/03_QGISへ取り込むためのデータ処理.md
      - 8.5 GISによる地形図作成法:
          - 概要: 08/05/index.md
          - 8.5.1 作業前の準備: 08/05/01_作業前の準備.md
          - 8.5.2 QGISの起動とファイルの保存: 08/05/02_QGISの起動とファイルの保存.md
          - 8.5.3 表示座標系の確認: 08/05/03_表示座標系の確認.md
          - 8.5.4 測量成果（点データ）の追加: 08/05/04_測量成果(点データ)の追加.md
          - 8.5.5 点データの内挿補間: 08/05/05_点データの内挿補間.md
          - 8.5.6 等高線の生成: 08/05/06_等高線の生成.md
          - 8.5.7 地物（建物・道・樹木・石等）の生成: 08/05/07_地物(建物・道・樹木・石等)の生成.md
          - 8.5.8 地形図を完成させる: 08/05/08_地形図を完成させる.md
      - 8.6 細部測量における内業の手順: 08/06_細部測量における内業の手順.md
  - 9. その他:
      - 概要: 09/index.md
      - 9.1 測量士補登録の手続き: 09/01_測量士補登録の手続き.md
      - 9.2 参考文献: 09/02_参考文献.md
